name: VanillaPlus
author: Skyzen
description: Améliorer votre expérience Survie avec de nouvelles fonctionnalités.

version: '1.0'
api-version: '1.21'

main: fr.skyzen.vanillaplus.VanillaPlus

commands:
  craft:
    description: "Crafter depuis n'importe où"
    aliases: [ ]

  help:
    description: "Liste des commandes du serveur"
    aliases: [ "aide" ]

  spawn:
    description: "Accéder au spawn"
    usage: "/spawn <create/delete>"
    aliases: [ "hub", "lobby" ]

  stats:
    description: "Statistiques des joueurs"
    aliases: [ "stat", "s" ]

  tp:
    description: "Téléportation à un joueur"
    usage: "/tp"
    aliases: [ "tpa", "teleport" ]

  warp:
    description: "Téléportation à un warp"
    usage: "/warp <create/delete> <nom>"
    aliases: [ "home" ]

  money:
    description: "Voir son argent"
    usage: "/money <add/remove> <montant> <joueur>"
    aliases: [ "balance", "bank", "argent" ]

  pay:
    description: "Envoyer de l'argent à un joueur"
    usage: "/pay <joueur> <montant>"
    aliases: [ ]

  market:
    description: "Hotêl des ventes"
    usage: "/market <sell> <prix>"

  msg:
    description: "Envoie un message à un joueur"
    usage: "/msg <joueur> <message>"
    aliases: [ "mp", "message", "messages" ]

  reply:
    description: "Répondre au dernier message"
    usage: "/reply <message>"

  msghistory:
    description: "Affiche l'historique des messages"
    usage: "/msghistory"

  nickname:
    description: "Acheter des couleurs et des icônes de pseudo."